export interface SegmentDef {
  name: string
  fields: Record<number, string>
}

export const SEGMENT_DEFS: Record<string, SegmentDef> = {
  MSH: {
    name: 'Message Header',
    fields: {
      1: 'Field Separator',
      2: 'Encoding Characters',
      3: 'Sending Application',
      4: 'Sending Facility',
      5: 'Receiving Application',
      6: 'Receiving Facility',
      7: 'Date/Time of Message',
      8: 'Security',
      9: 'Message Type',
      10: 'Message Control ID',
      11: 'Processing ID',
      12: 'Version ID',
      13: 'Sequence Number',
      14: 'Continuation Pointer',
      15: 'Accept Acknowledgment Type',
      16: 'Application Acknowledgment Type',
      17: 'Country Code',
      18: 'Character Set',
      19: 'Principal Language of Message',
      21: 'Message Profile Identifier',
    },
  },
  EVN: {
    name: 'Event Type',
    fields: {
      1: 'Event Type Code',
      2: 'Recorded Date/Time',
      3: 'Date/Time Planned Event',
      4: 'Event Reason Code',
      5: 'Operator ID',
      6: 'Event Occurred',
      7: 'Event Facility',
    },
  },
  PID: {
    name: 'Patient Identification',
    fields: {
      1: 'Set ID',
      2: 'Patient ID (Ext)',
      3: 'Patient Identifier List',
      4: 'Alternate Patient ID',
      5: 'Patient Name',
      6: "Mother's Maiden Name",
      7: 'Date/Time of Birth',
      8: 'Administrative Sex',
      9: 'Patient Alias',
      10: 'Race',
      11: 'Patient Address',
      12: 'County Code',
      13: 'Phone Number (Home)',
      14: 'Phone Number (Business)',
      15: 'Primary Language',
      16: 'Marital Status',
      17: 'Religion',
      18: 'Patient Account Number',
      19: 'SSN Number',
      20: "Driver's License Number",
      21: "Mother's Identifier",
      22: 'Ethnic Group',
      23: 'Birth Place',
      24: 'Multiple Birth Indicator',
      25: 'Birth Order',
      26: 'Citizenship',
      27: 'Veterans Military Status',
      28: 'Nationality',
      29: 'Patient Death Date and Time',
      30: 'Patient Death Indicator',
      31: 'Identity Unknown Indicator',
      32: 'Identity Reliability Code',
      33: 'Last Update Date/Time',
      34: 'Last Update Facility',
      35: 'Species Code',
      36: 'Breed Code',
      37: 'Strain',
      38: 'Production Class Code',
    },
  },
  PV1: {
    name: 'Patient Visit',
    fields: {
      1: 'Set ID',
      2: 'Patient Class',
      3: 'Assigned Patient Location',
      4: 'Admission Type',
      5: 'Preadmit Number',
      6: 'Prior Patient Location',
      7: 'Attending Doctor',
      8: 'Referring Doctor',
      9: 'Consulting Doctor',
      10: 'Hospital Service',
      11: 'Temporary Location',
      12: 'Preadmit Test Indicator',
      13: 'Re-admission Indicator',
      14: 'Admit Source',
      15: 'Ambulatory Status',
      16: 'VIP Indicator',
      17: 'Admitting Doctor',
      18: 'Patient Type',
      19: 'Visit Number',
      20: 'Financial Class',
      21: 'Charge Price Indicator',
      22: 'Courtesy Code',
      23: 'Credit Rating',
      24: 'Contract Code',
      25: 'Contract Effective Date',
      26: 'Contract Amount',
      27: 'Contract Period',
      28: 'Interest Code',
      29: 'Transfer to Bad Debt Code',
      30: 'Transfer to Bad Debt Date',
      31: 'Bad Debt Agency Code',
      32: 'Bad Debt Transfer Amount',
      33: 'Bad Debt Recovery Amount',
      34: 'Delete Account Indicator',
      35: 'Delete Account Date',
      36: 'Discharge Disposition',
      37: 'Discharged to Location',
      38: 'Diet Type',
      39: 'Servicing Facility',
      40: 'Bed Status',
      41: 'Account Status',
      42: 'Pending Location',
      43: 'Prior Temporary Location',
      44: 'Admit Date/Time',
      45: 'Discharge Date/Time',
      46: 'Current Patient Balance',
      47: 'Total Charges',
      48: 'Total Adjustments',
      49: 'Total Payments',
      50: 'Alternate Visit ID',
      51: 'Visit Indicator',
    },
  },
  PV2: {
    name: 'Patient Visit - Additional Info',
    fields: {
      1: 'Prior Pending Location',
      2: 'Accommodation Code',
      3: 'Admit Reason',
      4: 'Transfer Reason',
      5: 'Patient Valuables',
      6: 'Patient Valuables Location',
      7: 'Visit User Code',
      8: 'Expected Admit Date/Time',
      9: 'Expected Discharge Date/Time',
      10: 'Estimated Length of Inpatient Stay',
      11: 'Actual Length of Inpatient Stay',
      12: 'Visit Description',
      13: 'Referral Source Code',
      14: 'Previous Service Date',
      15: 'Employment Illness Related Indicator',
      16: 'Purge Status Code',
      17: 'Purge Status Date',
      18: 'Special Program Code',
      19: 'Retention Indicator',
      20: 'Expected Number of Insurance Plans',
      21: 'Visit Publicity Code',
      22: 'Visit Protection Indicator',
    },
  },
  NK1: {
    name: 'Next of Kin / Associated Parties',
    fields: {
      1: 'Set ID',
      2: 'Name',
      3: 'Relationship',
      4: 'Address',
      5: 'Phone Number',
      6: 'Business Phone Number',
      7: 'Contact Role',
      8: 'Start Date',
      9: 'End Date',
      10: 'Next of Kin / Associated Job Title',
      11: 'Next of Kin / Associated Job Code',
      12: 'Next of Kin / Associated Employee Number',
      13: 'Organization Name',
      14: 'Marital Status',
      15: 'Administrative Sex',
      16: 'Date/Time of Birth',
      17: 'Living Dependency',
      18: 'Ambulatory Status',
      19: 'Citizenship',
      20: 'Primary Language',
      21: 'Living Arrangement',
      22: 'Publicity Code',
      23: 'Protection Indicator',
      24: 'Student Indicator',
      25: 'Religion',
      26: "Mother's Maiden Name",
      27: 'Nationality',
      28: 'Ethnic Group',
      29: 'Contact Reason',
      30: 'Contact Person Name',
      31: 'Contact Person Telephone Number',
      32: 'Contact Person Address',
      33: 'Next of Kin Associated Organization Name',
      34: 'Next of Kin Job Status',
      35: 'Race',
      36: 'Handicap',
      37: 'Contact Person Social Security Number',
    },
  },
  ORC: {
    name: 'Common Order',
    fields: {
      1: 'Order Control',
      2: 'Placer Order Number',
      3: 'Filler Order Number',
      4: 'Placer Group Number',
      5: 'Order Status',
      6: 'Response Flag',
      7: 'Quantity/Timing',
      8: 'Parent Order',
      9: 'Date/Time of Transaction',
      10: 'Entered By',
      11: 'Verified By',
      12: 'Ordering Provider',
      13: 'Enterer\'s Location',
      14: 'Call Back Phone Number',
      15: 'Order Effective Date/Time',
      16: 'Order Control Code Reason',
      17: 'Entering Organization',
      18: 'Entering Device',
      19: 'Action By',
      21: 'Ordering Facility Name',
      22: 'Ordering Facility Address',
      23: 'Ordering Facility Phone Number',
      24: 'Ordering Provider Address',
    },
  },
  OBR: {
    name: 'Observation Request',
    fields: {
      1: 'Set ID',
      2: 'Placer Order Number',
      3: 'Filler Order Number',
      4: 'Universal Service Identifier',
      5: 'Priority',
      6: 'Requested Date/Time',
      7: 'Observation Date/Time',
      8: 'Observation End Date/Time',
      9: 'Collection Volume',
      10: 'Collector Identifier',
      11: 'Specimen Action Code',
      12: 'Danger Code',
      13: 'Relevant Clinical Information',
      14: 'Specimen Received Date/Time',
      15: 'Specimen Source',
      16: 'Ordering Provider',
      17: 'Order Callback Phone Number',
      18: 'Placer Field 1',
      19: 'Placer Field 2',
      20: 'Filler Field 1',
      21: 'Filler Field 2',
      22: 'Results Report/Status Change Date/Time',
      23: 'Charge to Practice',
      24: 'Diagnostic Service Section ID',
      25: 'Result Status',
      26: 'Parent Result',
      27: 'Quantity/Timing',
      28: 'Result Copies To',
      29: 'Parent Number',
      30: 'Transportation Mode',
      31: 'Reason for Study',
      32: 'Principal Result Interpreter',
      33: 'Assistant Result Interpreter',
      34: 'Technician',
      35: 'Transcriptionist',
      36: 'Scheduled Date/Time',
      37: 'Number of Sample Containers',
      38: 'Transport Logistics of Collected Sample',
      39: "Collector's Comment",
      40: 'Transport Arrangement Responsibility',
      41: 'Transport Arranged',
      42: 'Escort Required',
      43: 'Planned Patient Transport Comment',
      44: 'Procedure Code',
      45: 'Procedure Code Modifier',
      46: 'Placer Supplemental Service Information',
      47: 'Filler Supplemental Service Information',
    },
  },
  OBX: {
    name: 'Observation / Result',
    fields: {
      1: 'Set ID',
      2: 'Value Type',
      3: 'Observation Identifier',
      4: 'Observation Sub-ID',
      5: 'Observation Value',
      6: 'Units',
      7: 'Reference Range',
      8: 'Interpretation Codes',
      9: 'Probability',
      10: 'Nature of Abnormal Test',
      11: 'Observation Result Status',
      12: 'Effective Date of Reference Range',
      13: 'User Defined Access Checks',
      14: 'Date/Time of the Observation',
      15: "Producer's ID",
      16: 'Responsible Observer',
      17: 'Observation Method',
      18: 'Equipment Instance Identifier',
      19: 'Date/Time of the Analysis',
    },
  },
  NTE: {
    name: 'Notes and Comments',
    fields: {
      1: 'Set ID',
      2: 'Source of Comment',
      3: 'Comment',
      4: 'Comment Type',
    },
  },
  AL1: {
    name: 'Allergy Information',
    fields: {
      1: 'Set ID',
      2: 'Allergen Type Code',
      3: 'Allergen Code/Mnemonic/Description',
      4: 'Allergy Severity Code',
      5: 'Allergy Reaction Code',
      6: 'Identification Date',
    },
  },
  DG1: {
    name: 'Diagnosis',
    fields: {
      1: 'Set ID',
      2: 'Diagnosis Coding Method',
      3: 'Diagnosis Code',
      4: 'Diagnosis Description',
      5: 'Diagnosis Date/Time',
      6: 'Diagnosis Type',
      7: 'Major Diagnostic Category',
      8: 'Diagnostic Related Group',
      9: 'DRG Approval Indicator',
      10: 'DRG Grouper Review Code',
      11: 'Outlier Type',
      12: 'Outlier Days',
      13: 'Outlier Cost',
      14: 'Grouper Version and Type',
      15: 'Diagnosis Priority',
      16: 'Diagnosing Clinician',
      17: 'Diagnosis Classification',
      18: 'Confidential Indicator',
      19: 'Attestation Date/Time',
    },
  },
  PR1: {
    name: 'Procedures',
    fields: {
      1: 'Set ID',
      2: 'Procedure Coding Method',
      3: 'Procedure Code',
      4: 'Procedure Description',
      5: 'Procedure Date/Time',
      6: 'Procedure Functional Type',
      7: 'Procedure Minutes',
      8: 'Anesthesiologist',
      9: 'Anesthesia Code',
      10: 'Anesthesia Minutes',
      11: 'Surgeon',
      12: 'Procedure Practitioner',
      13: 'Consent Code',
      14: 'Procedure Priority',
      15: 'Associated Diagnosis Code',
      16: 'Procedure Code Modifier',
      17: 'Procedure DRG Type',
      18: 'Tissue Type Code',
      19: 'Procedure Identifier',
      20: 'Procedure Action Code',
    },
  },
  GT1: {
    name: 'Guarantor',
    fields: {
      1: 'Set ID',
      2: 'Guarantor Number',
      3: 'Guarantor Name',
      4: 'Guarantor Spouse Name',
      5: 'Guarantor Address',
      6: 'Guarantor Phone Number (Home)',
      7: 'Guarantor Phone Number (Business)',
      8: 'Guarantor Date/Time of Birth',
      9: 'Guarantor Administrative Sex',
      10: 'Guarantor Type',
      11: 'Guarantor Relationship',
      12: 'Guarantor SSN',
      13: 'Guarantor Date - Begin',
      14: 'Guarantor Date - End',
      15: 'Guarantor Priority',
      16: 'Guarantor Employer Name',
      17: 'Guarantor Employer Address',
      18: 'Guarantor Employer Phone Number',
      19: 'Guarantor Employee ID Number',
      20: 'Guarantor Employment Status',
      21: 'Guarantor Organization Name',
    },
  },
  IN1: {
    name: 'Insurance',
    fields: {
      1: 'Set ID',
      2: 'Insurance Plan ID',
      3: 'Insurance Company ID',
      4: 'Insurance Company Name',
      5: 'Insurance Company Address',
      6: 'Insurance Company Contact Person',
      7: 'Insurance Company Phone Number',
      8: 'Group Number',
      9: 'Group Name',
      10: "Insured's Group Employer ID",
      11: "Insured's Group Employer Name",
      12: 'Plan Effective Date',
      13: 'Plan Expiration Date',
      14: 'Authorization Information',
      15: 'Plan Type',
      16: "Name of Insured",
      17: "Insured's Relationship to Patient",
      18: "Insured's Date of Birth",
      19: "Insured's Address",
      20: 'Assignment of Benefits',
      21: 'Coordination of Benefits',
      22: 'Coord of Ben. Priority',
      23: 'Notice of Admission Flag',
      24: 'Notice of Admission Date',
      25: 'Report of Eligibility Flag',
      26: 'Report of Eligibility Date',
      27: 'Release Information Code',
      28: 'Pre-Admit Cert (PAC)',
      29: 'Verification Date/Time',
      30: 'Verification By',
      31: 'Type of Agreement Code',
      32: 'Billing Status',
      33: 'Lifetime Reserve Days',
      34: 'Delay Before L.R. Day',
      35: "Company Plan Code",
      36: 'Policy Number',
      37: 'Policy Deductible',
      38: 'Policy Limit - Amount',
      39: 'Policy Limit - Days',
      40: 'Room Rate - Semi-Private',
      41: 'Room Rate - Private',
      42: "Insured's Employment Status",
      43: "Insured's Administrative Sex",
      44: "Insured's Employer's Address",
      45: 'Verification Status',
      46: 'Prior Insurance Plan ID',
      47: 'Coverage Type',
      48: 'Handicap',
      49: "Insured's ID Number",
    },
  },
  MSA: {
    name: 'Message Acknowledgment',
    fields: {
      1: 'Acknowledgment Code',
      2: 'Message Control ID',
      3: 'Text Message',
      4: 'Expected Sequence Number',
      5: 'Delayed Acknowledgment Type',
      6: 'Error Condition',
    },
  },
  ERR: {
    name: 'Error',
    fields: {
      1: 'Error Code and Location',
      2: 'Error Location',
      3: 'HL7 Error Code',
      4: 'Severity',
      5: 'Application Error Code',
      6: 'Application Error Parameter',
      7: 'Diagnostic Information',
      8: 'User Message',
      9: 'Inform Person Indicator',
      10: 'Override Type',
      11: 'Override Reason Code',
      12: 'Help Desk Contact Point',
    },
  },
  SCH: {
    name: 'Scheduling Activity Information',
    fields: {
      1: 'Placer Appointment ID',
      2: 'Filler Appointment ID',
      3: 'Occurrence Number',
      4: 'Placer Group Number',
      5: 'Schedule ID',
      6: 'Event Reason',
      7: 'Appointment Reason',
      8: 'Appointment Type',
      9: 'Appointment Duration',
      10: 'Appointment Duration Units',
      11: 'Appointment Timing Quantity',
      12: 'Placer Contact Person',
      13: 'Placer Contact Phone Number',
      14: 'Placer Contact Address',
      15: 'Placer Contact Location',
      16: 'Filler Contact Person',
      17: 'Filler Contact Phone Number',
      18: 'Filler Contact Address',
      19: 'Filler Contact Location',
      20: 'Entered By Person',
      21: 'Entered By Phone Number',
      22: 'Entered By Location',
      23: 'Parent Placer Appointment ID',
      24: 'Parent Filler Appointment ID',
      25: 'Filler Status Code',
    },
  },
  RXO: {
    name: 'Pharmacy / Treatment Order',
    fields: {
      1: 'Requested Give Code',
      2: 'Requested Give Amount - Minimum',
      3: 'Requested Give Amount - Maximum',
      4: 'Requested Give Units',
      5: 'Requested Dosage Form',
      6: "Provider's Pharmacy/Treatment Instructions",
      7: "Provider's Administration Instructions",
      8: 'Deliver To Location',
      9: 'Allow Substitutions',
      10: 'Requested Dispense Code',
      11: 'Requested Dispense Amount',
      12: 'Requested Dispense Units',
      13: 'Number of Refills',
      14: "Ordering Provider's DEA Number",
      15: "Pharmacist/Treatment Supplier's Verifier ID",
      16: 'Needs Human Review',
      17: 'Requested Give Per (Time Unit)',
      18: 'Requested Give Strength',
      19: 'Requested Give Strength Units',
      20: 'Indication',
      21: 'Requested Give Rate Amount',
      22: 'Requested Give Rate Units',
      23: 'Total Daily Dose',
    },
  },
  RXE: {
    name: 'Pharmacy / Encoded Order',
    fields: {
      1: 'Quantity/Timing',
      2: 'Give Code',
      3: 'Give Amount - Minimum',
      4: 'Give Amount - Maximum',
      5: 'Give Units',
      6: 'Give Dosage Form',
      7: "Provider's Administration Instructions",
      8: 'Deliver To Location',
      9: 'Substitution Status',
      10: 'Dispense Amount',
      11: 'Dispense Units',
      12: 'Number of Refills',
      13: "Ordering Provider's DEA Number",
      14: "Pharmacist/Treatment Supplier's Verifier ID",
      15: 'Prescription Number',
      16: 'Number of Refills Remaining',
      17: 'Number of Refills/Doses Dispensed',
      18: 'Date/Time of Most Recent Refill',
      19: 'Total Daily Dose',
      20: 'Needs Human Review',
      21: "Pharmacist/Treatment Supplier's Verifier ID",
      22: 'Pharmacy/Treatment Supplier\'s Special Dispensing Instructions',
      23: 'Give Per (Time Unit)',
      24: 'Give Rate Amount',
      25: 'Give Rate Units',
      26: 'Give Strength',
      27: 'Give Strength Units',
      28: 'Give Indication',
      29: 'Dispense Package Size',
      30: 'Dispense Package Size Unit',
      31: 'Dispense Package Method',
    },
  },
  RXA: {
    name: 'Pharmacy / Treatment Administration',
    fields: {
      1: 'Give Sub-ID Counter',
      2: 'Administration Sub-ID Counter',
      3: 'Date/Time Start of Administration',
      4: 'Date/Time End of Administration',
      5: 'Administered Code',
      6: 'Administered Amount',
      7: 'Administered Units',
      8: 'Administered Dosage Form',
      9: 'Administration Notes',
      10: 'Administering Provider',
      11: 'Administered-at Location',
      12: 'Administered Per (Time Unit)',
      13: 'Administered Strength',
      14: 'Administered Strength Units',
      15: 'Substance Lot Number',
      16: 'Substance Expiration Date',
      17: 'Substance Manufacturer Name',
      18: 'Substance/Treatment Refusal Reason',
      19: 'Indication',
      20: 'Completion Status',
      21: 'Action Code - RXA',
      22: 'System Entry Date/Time',
    },
  },
  RXR: {
    name: 'Pharmacy / Route',
    fields: {
      1: 'Route',
      2: 'Administration Site',
      3: 'Administration Device',
      4: 'Administration Method',
      5: 'Routing Instruction',
      6: 'Administration Site Modifier',
    },
  },
  SPM: {
    name: 'Specimen',
    fields: {
      1: 'Set ID',
      2: 'Specimen ID',
      3: 'Specimen Parent IDs',
      4: 'Specimen Type',
      5: 'Specimen Type Modifier',
      6: 'Specimen Additives',
      7: 'Specimen Collection Method',
      8: 'Specimen Source Site',
      9: 'Specimen Source Site Modifier',
      10: 'Specimen Collection Site',
      11: 'Specimen Role',
      12: 'Specimen Collection Amount',
      13: 'Grouped Specimen Count',
      14: 'Specimen Description',
      15: 'Specimen Handling Code',
      16: 'Specimen Risk Code',
      17: 'Specimen Collection Date/Time',
      18: 'Specimen Received Date/Time',
      19: 'Specimen Expiration Date/Time',
      20: 'Specimen Availability',
      21: 'Specimen Reject Reason',
      22: 'Specimen Quality',
      23: 'Specimen Appropriateness',
      24: 'Specimen Condition',
      25: 'Specimen Current Quantity',
      26: 'Number of Specimen Containers',
      27: 'Container Type',
      28: 'Container Condition',
      29: 'Specimen Child Role',
    },
  },
  ROL: {
    name: 'Role',
    fields: {
      1: 'Role Instance ID',
      2: 'Action Code',
      3: 'Role',
      4: 'Role Person',
      5: 'Role Begin Date/Time',
      6: 'Role End Date/Time',
      7: 'Role Duration',
      8: 'Role Action Reason',
      9: 'Provider Type',
      10: 'Organization Unit Type',
      11: 'Office/Home Address/Birthplace',
      12: 'Phone',
    },
  },
  QRD: {
    name: 'Query Definition',
    fields: {
      1: 'Query Date/Time',
      2: 'Query Format Code',
      3: 'Query Priority',
      4: 'Query ID',
      5: 'Deferred Response Type',
      6: 'Deferred Response Date/Time',
      7: 'Quantity Limited Request',
      8: 'Who Subject Filter',
      9: 'What Subject Filter',
      10: 'What Department Data Code',
      11: 'What Data Code Value Qualifier',
      12: 'Query Results Level',
    },
  },
  ZPI: {
    name: 'Custom - Patient Insurance (Z-Segment)',
    fields: {},
  },
}

export function getSegmentName(id: string): string {
  return SEGMENT_DEFS[id]?.name ?? (id.startsWith('Z') ? `Custom Segment (${id})` : `Unknown Segment (${id})`)
}

export function getFieldName(segmentId: string, fieldIndex: number): string {
  return SEGMENT_DEFS[segmentId]?.fields[fieldIndex] ?? `Field ${fieldIndex}`
}
